from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Profile)
admin.site.register(PermissionLevel)
admin.site.register(UserRole)
admin.site.register(UserSetting)
admin.site.register(SubscriptionTranasction)
admin.site.register(RegisteredDevice)
admin.site.register(Team)
admin.site.register(MemberInvite)
admin.site.register(Blog)
admin.site.register(SavedBlogSectionHead)
admin.site.register(SavedBlogEdit)
admin.site.register(BlogSection)
admin.site.register(SocialPost)
admin.site.register(SocialPlatform)
admin.site.register(BlogSocialPost)
admin.site.register(ContentImprover)
admin.site.register(Paragraph)
admin.site.register(Sentence)
admin.site.register(ArticleTitle)
admin.site.register(MetaDescription)
admin.site.register(ContentSummary)
admin.site.register(LandingPageCopy)
admin.site.register(RequestsQueue)
admin.site.register(SubscriptionPackage)
admin.site.register(ToneOfVoice)
admin.site.register(TeamClient)
admin.site.register(ClientCategory)
